export const PASSWORD_LOCK_TTYPE_DICT = {
    PASSWORD_LOCK_TTYPE_COMMON: 1, // 普通
    PASSWORD_LOCK_TTYPE_CUSTOM: 2, // 自定义
}

export const PASSWORD_LOCK_TTYPE_LIST = [
    [PASSWORD_LOCK_TTYPE_DICT.PASSWORD_LOCK_TTYPE_COMMON, '普通'],
    [PASSWORD_LOCK_TTYPE_DICT.PASSWORD_LOCK_TTYPE_CUSTOM, '自定义'],
]
